### ISSUE TITLE
`bind --erase -all` is erasing ALL keybindings

### ISSUE THREAD

**Issue by IndianBoy42** [oh-my-fish/plugin-bang-bang#14]
https://github.com/oh-my-fish/plugin-bang-bang/blob/816c66df34e1cb94a476fa6418d46206ef84e8d3/conf.d/plugin-bang-bang.fish#L2

Quote from the fish help (3.6.0): "Specifying -a or --all without -M or --mode erases all binds in all modes *regardless of sequence.*" (emphasis mine)

I think the intention was to erase `!` and `$` from all modes? Instead its just erasing every other plugins keybindings

**Comment by StefanLobbenmeierObjego** [comment]
Yeah, I was confused why `jorgebucaran/autopair.fish` stopped working suddenly, and now I noticed that it works when I remove `oh-my-fish/plugin-bang-bang`, so it seems this is breaking it

**Comment by scorphus** [comment]
I'm definitely missing something here. Can any of you please help with any reproduction steps?

This is what I get so far, no bindings erased:

```
⋊> ~ bind | wc -l
118
⋊> ~ omf install bang-bang
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package bang-bang
✔ bang-bang successfully installed.
⋊> ~ bind | wc -l
120
⋊> ~ exec fish -li
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
⋊> ~ bind | wc -l
120
⋊> ~ omf uninstall bang-bang
bang-bang successfully removed.
⋊> ~ bind | wc -l
118
⋊> ~ exec fish -li
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
⋊> ~ bind | wc -l
118
⋊> ~
```

Thanks in advance.

**Comment by IndianBoy42** [comment]
perhaps it only happens if there are other snippets sourced earlier in `conf.d`. For example the `jorgebucaran/autopair.fish` plugin mentioned before. 

I have 
```fish
 conf.d
├──  _tide_init.fish
├──  autopair.fish
├──  autovenv.fish
├──  bak.fish
├──  fish_auto_source.fish
├──  forgit.plugin.fish
├──  fzf.fish
├──  nix.fish
├──  nvm.fish
├──  on_dir_change.fish
├──  park.fish
├──  plugin-bang-bang.fish
└──  run_history_commands.fish
```

I'm not sure what more I can do as I dont have the time or ability to make reproduction steps from a clean install

With this 
```fish
    bind | wc -l
    bind --erase --all !
    bind --erase --all '$'
    bind | wc -l
```
in `plugin-bang-bang.fish` I can see
```
43
18
```
while 
```fish
    bind | wc -l
    bind --erase !
    bind --erase '$'
    bind | wc -l
```
gives

```
43
43
```

By the help docs of fish `bind`  this use of `bind` is clearly wrong though
