### ISSUE TITLE
Compatibility with new fisher release

### ISSUE THREAD

**Issue by diegoferigo** [oh-my-fish/plugin-bang-bang#7]
Installing this plugin with the latest fisher, I get the following error:

```
fisher: Plugin not supported: "oh-my-fish/plugin-bang-bang"
```

**Comment by diegoferigo** [comment]
Moving the files from `~/.config/fish/functions` to `~/.config/fish/completions` fixes the problem, would you accept a PR?

**Comment by diegoferigo** [comment]
Moving the file `key_bindings.fish` into `~/.config/fish/completions` solves the problem.

**Comment by maparent** [comment]
you can install petertriho/plugin-bang-bang in the meantime

**Comment by philipbjorge** [comment]
On fisher 4.4.3, running `fisher install  "oh-my-fish/plugin-bang-bang"` succeeds.
It looks like the fix landed Feb 2021? I think this issue can be closed.

Thanks for the awesome plugin!
